# Generated by Django 4.2.24 on 2025-10-29 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date']},
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
