# Generated by Django 4.2.24 on 2025-10-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
